### ISSUE TITLE
Spotted in logs

### ISSUE THREAD

**Issue by darknight7** [Phala-Network/khala-parachain#63]
```phala-node    | Version: 0.1.10-0911026-x86_64-linux-gnu
phala-node    |
phala-node    |    0: sp_panic_handler::set::{{closure}}
phala-node    |    1: std::panicking::rust_panic_with_hook
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:610:17
phala-node    |    2: std::panicking::begin_panic_handler::{{closure}}
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:500:13
phala-node    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/sys_common/backtrace.rs:139:18
phala-node    |    4: rust_begin_unwind
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:498:5
phala-node    |    5: core::panicking::panic_fmt
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/panicking.rs:106:14
phala-node    |    6: <khala_parachain_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,khala_parachain_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<khala_parachain_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<khala_parachain_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<khala_parachain_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<khala_parachain_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<khala_parachain_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<khala_parachain_runtime::Runtime>,phala_pallets::mq::check_seq::CheckMqSequence<khala_parachain_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<khala_parachain_runtime::Runtime>)>>>>::execute_block
phala-node    |    7: std::panicking::try
phala-node    |    8: sp_externalities::scope_limited::set_and_run_with_externalities
phala-node    |    9: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
phala-node    |   10: sc_executor::wasm_runtime::RuntimeCache::with_instance
phala-node    |   11: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
phala-node    |   12: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
phala-node    |   13: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
phala-node    |   14: <khala_parachain_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
phala-node    |   15: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
phala-node    |   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
phala-node    |   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
phala-node    |   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
phala-node    |   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
phala-node    |   20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
phala-node    |   21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
phala-node    |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
phala-node    |   23: tokio::park::thread::CachedParkThread::block_on
phala-node    |   24: tokio::runtime::task::raw::poll
phala-node    |   25: std::sys_common::backtrace::__rust_begin_short_backtrace
phala-node    |   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
phala-node    |   27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/alloc/src/boxed.rs:1694:9
phala-node    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/alloc/src/boxed.rs:1694:9
phala-node    |       std::sys::unix::thread::Thread::new::thread_start
phala-node    |              at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/sys/unix/thread.rs:106:17
phala-node    |   28: start_thread
phala-node    |   29: clone
phala-node    |
phala-node    |
phala-node    | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/d36550a/frame/executive/src/lib.rs:488
phala-node    |
phala-node    | This is a bug. Please report it at:
phala-node    |
phala-node    |         https://github.com/Phala-Network/khala-parachain/issues/new
phala-node    |
phala-node    | 2022-02-08 22:27:11 [Parachain] panicked at 'Storage root must match that calculated.', /home/h4x/.cargo/git/checkouts/substrate-7e08433d4c370a21/d36550a/frame/executive/src/lib.rs:488:9
phala-node    | 2022-02-08 22:27:11 [Parachain] Block prepare storage changes error:
phala-node    | RuntimeApiError(Application(Execution(Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x5ce8 - <unknown>!rust_begin_unwind\n    1: 0x274a - <unknown>!core::panicking::panic_fmt::h8f11323637b4db3b\n    2: 0xdbfc9 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h8614e9cd1ce2fa16\n    3: 0x2c46a9 - <unknown>!Core_execute_block\n"))))
phala-node    | 2022-02-08 22:27:11 [Parachain] 💔 Error importing block 0x56653de29abadc78ec179faa40ace1ac6956f34cb784439bcc770f7f747f1fd3: Err(Other(ClientImport("Error at calling runtime api: Execution failed: Other(\"Wasm execution trapped: wasm trap: unreachable\\nwasm backtrace:\\n    0: 0x5ce8 - <unknown>!rust_begin_unwind\\n    1: 0x274a - <unknown>!core::panicking::panic_fmt::h8f11323637b4db3b\\n    2: 0xdbfc9 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::h8614e9cd1ce2fa16\\n    3: 0x2c46a9 - <unknown>!Core_execute_block\\n\")")))
phala-node    | 2022-02-08 22:27:12 [Relaychain] ✨ Imported #11323789 (0xa206…7daa)
```

**Comment by jasl** [comment]
Unfortunately this is an upstream bug https://github.com/paritytech/cumulus/issues/607
we've logged here https://github.com/Phala-Network/phala-blockchain/issues/551

for workaround, you can add `--state-cache-size 0` but it will impact performance significantly
