### ISSUE TITLE
Core Dump on Phala-Node container while syncing Pherry

### ISSUE THREAD

**Issue by jimiflowers** [Phala-Network/khala-parachain#99]
Hi. I'm getting these errors on phala-node while trying to sync pherry. I'm running solo-mining on latest version and docker images are updated as well. I don't know if it's a specific error or it's a bug:

```
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:10 [Relaychain] 💤 Idle (30 peers), best: #12391689 (0xc13e…48dc), finalized #12391686 (0xd44a…c88a), ⬇ 104.9kiB/s ⬆ 268.1kiB/s   
phala-node | 2022-04-24 11:48:12 [Relaychain] ✨ Imported #12391690 (0x3407…51f0)
phala-node | 2022-04-24 11:48:13 [Parachain] ⚙️ Syncing 0.0 bps, target=#1521786 (17 peers), best: #1521700 (0x4a8f…1f73), finalized #1521700 (0x4a8f…1f73), ⬇ 155.1kiB/s ⬆ 3.1kiB/s
phala-node | 2022-04-24 11:48:15 [Relaychain] 💤 Idle (29 peers), best: #12391690 (0x3407…51f0), finalized #12391686 (0xd44a…c88a), ⬇ 187.1kiB/s ⬆ 349.6kiB/s   
phala-node | 2022-04-24 11:48:16 [Parachain] panicked at 'Transaction will be valid in the future', /home/h4x/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/frame/executive/src/lib.rs:388:17
phala-node | 2022-04-24 11:48:16 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:16 [Parachain] 💔 Error importing block 0x3a7213b5f5203ce5be1656dc67a55817e49e749493d21cb1973cec2d5adf85db: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:18 [Relaychain] ✨ Imported #12391691 (0x548f…ec34)
phala-node | 2022-04-24 11:48:18 [Parachain] ⚙️ Syncing 0.0 bps, target=#1521787 (17 peers), best: #1521700 (0x4a8f…1f73), finalized #1521700 (0x4a8f…1f73), ⬇ 347.2kiB/s ⬆ 3.1kiB/s
phala-node | 2022-04-24 11:48:18 [Parachain] panicked at 'Transaction will be valid in the future', /home/h4x/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/frame/executive/src/lib.rs:388:17
phala-node | 2022-04-24 11:48:18 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:18 [Parachain] 💔 Error importing block 0x3a7213b5f5203ce5be1656dc67a55817e49e749493d21cb1973cec2d5adf85db: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:20 [Relaychain] 💤 Idle (30 peers), best: #12391691 (0x548f…ec34), finalized #12391687 (0x10b7…d18d), ⬇ 267.7kiB/s ⬆ 408.1kiB/s   
phala-node | 2022-04-24 11:48:23 [Parachain] ⚙️ Syncing 0.0 bps, target=#1521786 (17 peers), best: #1521700 (0x4a8f…1f73), finalized #1521700 (0x4a8f…1f73), ⬇ 82.7kiB/s ⬆ 2.4kiB/s
phala-node | 2022-04-24 11:48:24 [Relaychain] ✨ Imported #12391692 (0x37e9…ebbc)
phala-node | 2022-04-24 11:48:25 [Parachain] panicked at 'Transaction will be valid in the future', /home/h4x/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/frame/executive/src/lib.rs:388:17
phala-node | 2022-04-24 11:48:25 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:25 [Parachain] 💔 Error importing block 0x3a7213b5f5203ce5be1656dc67a55817e49e749493d21cb1973cec2d5adf85db: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:25 [Relaychain] 💤 Idle (30 peers), best: #12391692 (0x37e9…ebbc), finalized #12391689 (0xc13e…48dc), ⬇ 750.9kiB/s ⬆ 635.7kiB/s   
phala-node | 2022-04-24 11:48:27 [Parachain] panicked at 'Transaction will be valid in the future', /home/h4x/.cargo/git/checkouts/substrate-7e08433d4c370a21/fc3fd07/frame/executive/src/lib.rs:388:17
phala-node | 2022-04-24 11:48:27 [Parachain] Block prepare storage changes error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:27 [Parachain] 💔 Error importing block 0x3a7213b5f5203ce5be1656dc67a55817e49e749493d21cb1973cec2d5adf85db: consensus error: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
phala-node | WASM backtrace:
phala-node |
phala-node | 0: 0x9b7b - <unknown>!rust_begin_unwind
phala-node | 1: 0x1d43 - <unknown>!core::panicking::panic_fmt::h038028a9926e2771
phala-node | 2: 0x27aea4 - <unknown>!core::panicking::panic_display::h656450c1cd186e0e
phala-node | 3: 0x2782a1 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::execute_block::hcbf439b5561e9f9f
phala-node | 4: 0x298902 - <unknown>!Core_execute_block
phala-node |
phala-node | 2022-04-24 11:48:28 [Parachain] ⚙️ Syncing 0.0 bps, target=#1521786 (17 peers), best: #1521700 (0x4a8f…1f73), finalized #1521700 (0x4a8f…1f73), ⬇ 473.5kiB/s ⬆ 3.0kiB/s
phala-node | 2022-04-24 11:48:30 [Relaychain] ✨ Imported #12391693 (0x96c7…ee0c)
phala-node | 2022-04-24 11:48:30 [Relaychain] ♻️ Reorg on #12391693,0x96c7…ee0c to #12391693,0xf191…1ff0, common ancestor #12391692,0x37e9…ebbc
phala-node | 2022-04-24 11:48:30 [Relaychain] ✨ Imported #12391693 (0xf191…1ff0)
```

**Comment by jimiflowers** [comment]
Yes, I tried restarting node (and also restarting all containers) but the error occurs again and again. I thought this error only occurred when pherry was already 100% synchronized, so, can I apply the workaround --state-cache-size while pherry is still synchronizing?

**Comment by jasl** [comment]
> Yes, I tried restarting node (and also restarting all containers) but the error occurs again and again. I thought this error only occurred when pherry was already 100% synchronized, so, can I apply the workaround --state-cache-size while pherry is still synchronizing?

you have to restart khala-node when you apply `--state-cache-size 0` arg

**Comment by jimiflowers** [comment]
Ok, I will try to sync pherry whith ```--state-cache-size 0``` set. Thanks for your time and sorry for the duplication.
